### PR TITLE
[MOB-2328] Update to Robolectric 4.4

### PR DESCRIPTION
**Pull request by vbabenkoru**

### CODE REVIEW

**Comment by Ayyanchira** [comment]
Looks like we need to call idling methods at more places where tests are waiting for methods to get invoked as reported in travis.

**Comment by vbabenkoru** [comment]
@Ayyanchira Yeah.. It ran successfully on my machine, but I guess Travis has different concurrency and it picked up things that were missed in local test runs.

**Comment by vbabenkoru** [comment]
@Ayyanchira Fixed!

**Comment by Ayyanchira** [comment]
Wow.. 👌👌👌
Looks like this will also help in jwt auth testing...

**Review by Ayyanchira — APPROVED** [review]

**Pull request merged**
