### PR TITLE
[MOB-4666] in-app in memory config option

### PR DESCRIPTION
**Pull request by roninopf**
## 🔹 Jira Ticket(s) if any

* [MOB-4666](https://iterable.atlassian.net/browse/MOB-4666)

## ✏️ Description

* adds an `IterableConfig` option to switch between storing on file (as before, and still default) or just in memory

### CODE REVIEW

**Review by Ayyanchira — COMMENTED** [review]
Looking good so far. Will wait for the file deletion for approval.

**Review by evangreer91 — COMMENTED** [review]
Looks good to me. The IterableInAppMemoryStorage method is not implemented, but I assume this is planned to be implemented in another PR.

**Comment by roninopf** [comment]
> Looks good to me. The IterableInAppMemoryStorage method is not implemented, but I assume this is planned to be implemented in another PR.

No, it just has an empty constructor, since nothing else needs to be setup when in memory storage is used.

**Review by evangreer91 — APPROVED** [review]
LGTM

**Pull request closed without merging**
