### PR TITLE
Added Beta SDK ToS to README; added link to Iterable's Android SDK re…

### PR DESCRIPTION
**Pull request by bradumbaugh**
- Added the Beta SDK terms of service to the README
- Added a link to Iterable's Android release notes

### CODE REVIEW

**Comment by bradumbaugh** [comment]
@vbabenkoru Any concerns with this? Would like to get this merged in today.

**Comment by bradumbaugh** [comment]
@vbabenkoru No; it's just it is just only applicable to beta versions.

**Comment by bradumbaugh** [comment]
@vbabenkoru Would it be better if I added this text under the beta heading?

> The following terms of service apply to beta versions of Iterable's Android SDK

**Comment by vbabenkoru** [comment]
What do you think about having this in a separate file, like `BETA-TOS.md`, and linking to it from release notes/changelogs for beta versions?

**Comment by bradumbaugh** [comment]
@vbabenkoru I think that's a good plan, went ahead and made that change.

**Pull request merged**
