### PR TITLE
MOB-5132: Fix deep link issue after app is opened from notification

### PR DESCRIPTION
**Pull request by devcsomnicg**
## 🔹 Jira Ticket(s) if any

* [MOB-5132](https://iterable.atlassian.net/browse/MOB-5132)

## ✏️ Description

> Fix deep link issue after app is opened from notification

[MOB-5132]: https://iterable.atlassian.net/browse/MOB-5132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by devcsomnicg** [comment]
@roninopf Could you please start review for this ?

**Comment by devcsomnicg** [comment]
@roninopf We are waiting for the review of this. Please review and let us know if any issues.

**Comment by Ayyanchira** [comment]
https://github.com/Iterable/iterable-android-sdk/assets/22951141/f3ade915-18a6-41bd-92b2-beb6a1583e00

The handler is still not called when the app is minimized or foregrounded. Only when the app is killed the handler works. Somehow the added flag of Intent.FLAG_ACTIVITY_CLEAR_TASK does not help in RN SDK

**Comment by devcsomnicg** [comment]
Hi @Ayyanchira I am not sure why it would not work on your end but can you please try uninstalling the app and then install it again.

Here are the videos of custom action handler and url handler working with CLEAR TASK.

https://drive.google.com/file/d/1v_8nTGrgMNuDS83uFIEBXyQxdQXo0_MP/view?usp=sharing
https://drive.google.com/file/d/1GrZLQG1xapjNg5gYyxffAXtyvQ24N1hY/view?usp=sharing

**Comment by Ayyanchira** [comment]
Looks good. Merging with master replica for final test run

**Pull request merged**
